### ISSUE TITLE
[Open VSX] FOSS VSCode extensions marketplace publishing

### ISSUE THREAD

**Issue by HoloTheDrunk** [pixldev/bevy-snippets#1]
The extension is currently unavailable on the [Open VSX extensions marketplace](https://github.com/open-vsx/publish-extensions).
Would it be possible to publish it there for the people using the FOSS build of VSCode?

**Comment by auyer** [comment]
Hi @pixldev ! Just wondering if you had a chance to look at it !

**Comment by maxsroka** [comment]
Hey, as this is an open source project, anyone can publish it there if they need to.
