### ISSUE TITLE
Please add snippet for Plugin and region comments

### ISSUE THREAD

**Issue by kristianmandrup** [pixldev/bevy-snippets#2]
Please also update snippets for bevy 0.9 as needed and provide a list of prefixes for each snippet included in the Readme.

I'd love to see support for regions as follows

```json
  "Rust Region": {
    "prefix": "region",
    "body": ["// region: --- $1", "\t ${0}", "// endregion: --- $1"],
    "description": "Region space"
  }
```

and `Plugin` as follows

```
pub struct ${1};
impl Plugin for ${1} {
    fn build(&self, app: &mut App) {
        app
            .${0}
    }
}
```

See this https://github.com/ryo33/vscode-bevy-snippet/blob/main/snippets/snippets.code-snippets

Cheers :)

**Comment by maxsroka** [comment]
I've added a plugin snippet, updated the readme and changed a few other things in #3.
Regions won't be added as they aren't specific to Bevy.
Thanks!

**Comment by kristianmandrup** [comment]
Cool 😎 Thanks
